[build]
publish = "public"
command = "zola build"

[build.environment]
ZOLA_VERSION = "0.8.0"

# The magic for deploying previews of branches
# We need to override the base url with whatever url Netlify assigns to our
# preview site.  We do this using the Netlify environment variable
# `$DEPLOY_PRIME_URL`.
[context.deploy-preview]
command = "zola build --base-url $DEPLOY_PRIME_URL"
